### ISSUE TITLE
Doesn't work with activeadmin file upload

### ISSUE THREAD

**Issue by danglduy** [aki77/activestorage-validator#1]
Hi,

Thanks for making this gem. I am working on using ActiveStorage for storing files uploaded from activeadmin's formtastic inputs. However, this gem seems not to be working with ActiveAdmin.

Although it does raise errors after the file with invalid extension was uploaded, the file is still stored in the storage.

Version:
- Rails 5.2.1
- Activeadmin 1.3.1
- activestorage-validator 0.1.0
- has_one_attached :file

**Comment by aki77** [comment]
That is a problem with ActiveStorage.
https://github.com/rails/rails/search?q=active+storage+transaction&type=Issues

**Comment by PSM8493** [comment]
I wonder if this issue was solved? I have the same problem with ActiveAdmin.
