### ISSUE TITLE
question about how it works

### ISSUE THREAD

**Issue by BKSpurgeon** [aki77/activestorage-validator#10]
Hi there

will the file still be uploaded to the bucket if there is a validation error? Looks like it will add errors (see here: https://github.com/aki77/activestorage-validator/blob/master/lib/activestorage/validator/blob.rb) but am ensure whether it will still upload the file to the google bucket. 

any pointers would be much appreciated.

chrs

**Comment by aki77** [comment]
That is an activestorage issue.
Maybe solved with rails6.
