### ISSUE TITLE
Content type Question

### ISSUE THREAD

**Issue by Tiltorito** [aki77/activestorage-validator#13]
Hello,

I am wondering if the content type is enough to validate the file type. Content type is given by the user, which means they can give whatever they want. 

Wouldn't it be useful to validate the extension of the file?

**Comment by aki77** [comment]
I think the file extension can be specified more freely by the user.
I think it's best to examine the contents of the file, but I don't think it's the role of this gem.
You can use the accept attribute of the input tag to limit by extension.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#attr-accept
