### ISSUE TITLE
has_many_attached validates the size of each individual attachment, correct?

### ISSUE THREAD

**Issue by eimermusic** [aki77/activestorage-validator#15]
Hi,

It was not absolutely sure this gem validated the individual sizes of each file in a has_many_attached or if it validated the size of all files combined in the association. I could kind-of see a use for both.

I checked the specs. They did not explicitly validate the size in a many relationship with multiple files.

I read the implementation to mean that it in fact does treat each file individually and does not do *combined* size validation.

I did figure it out (I think) but it might be useful to clarify this in the README?

Thanks for a great gem, btw.

**Comment by aki77** [comment]
Thank you.
That's certainly true.
If you can send me a PR, I'll merge it!

**Comment by aki77** [comment]
Thanks for the pull request!
