### ISSUE TITLE
*.ts can't pass on validate of video when i using direct upload.

### ISSUE THREAD

**Issue by x1wins** [aki77/activestorage-validator#17]
i can't upload *.ts extension file. (*.ts is video file extension)
this *.ts can't pass on validate when i using direct upload. 

but this is working well passing validate when not using direct upload.
i use below code with content_type: :video
```
class Encode < ApplicationRecord
  validates :file, presence: true, blob: { content_type: :video } # supported options: :image, :audio, :video, :text
end
```
https://github.com/x1wins/CW-OVP/issues/5

**Comment by aki77** [comment]
This is probably due to the content type not being set correctly during direct uploads.

https://github.com/rails/rails/blob/master/activestorage/app/models/active_storage/blob.rb#L168-L170

**Comment by x1wins** [comment]
> This is probably due to the content type not being set correctly during direct uploads.
> 
> https://github.com/rails/rails/blob/master/activestorage/app/models/active_storage/blob.rb#L168-L170

thanks you.
I have checked your link for validate code of video.
you are right.
File mime type has been application/octet-stream.

I checked two point and found that content-type was application/octet-stream
1. direct upload log
```
web_1      | Processing by ActiveStorage::DirectUploadsController#create as JSON
web_1      |   Parameters: {"blob"=>{"filename"=>"sample_1920x1080.ts", "content_type"=>"application/octet-stream", "byte_size"=>15074780, "checksum"=>"VeJxcPFo/qs9pPbwfSFdQw=="}, "direct_upload"=>{"blob"=>{"filename"=>"sample_1920x1080.ts", "content_type"=>"application/octet-stream", "byte_size"=>15074780, "checksum"=>"VeJxcPFo/qs9pPbwfSFdQw=="}}}
web_1      |    (0.9ms)  BEGIN
web_1      |   ActiveStorage::Blob Create (0.6ms)  INSERT INTO "active_storage_blobs" ("key", "filename", "content_type", "byte_size", "checksum", "created_at") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"  [["key", "kzatm1dk3ke5dkxrwbgajbcpxnfb"], ["filename", "sample_1920x1080.ts"], ["content_type", "application/octet-stream"], ["byte_size", 15074780], ["checksum", "VeJxcPFo/qs9pPbwfSFdQw=="], ["created_at", "2020-07-28 06:40:19.234414"]]
```
2. original file content-type
```
$ file --mime-type /Users/xxx/Downloads/sample_1920x1080.ts 
/Users/xxx/Downloads/sample_1920x1080.ts: application/octet-stream
```

**Comment by aki77** [comment]
I think you need to explicitly set the content_type when direct uploading.

https://github.com/rails/rails/pull/38124

**Comment by x1wins** [comment]
They fixed this issue
https://github.com/rails/rails/issues/39944
