### ISSUE TITLE
Help with .xlsm files pls

### ISSUE THREAD

**Issue by JohnDBR** [aki77/activestorage-validator#19]
Hello!

I've been having problems to upload an **.xlsm** file (Excel with macros) I'm using this mime-type **application/vnd.ms-excel.sheet.macroEnabled.12** I got it from [here](https://docs.microsoft.com/es-es/archive/blogs/vsofficedeveloper/office-2007-file-format-mime-types-for-http-content-streaming-2) and also [here](https://htmlstrip.com/mime-file-type-checker). However, I keep receiving a model error `{upload_fail: {file: ["is not a valid file format"]}}` and my gem usage is standard i guess.

`validates :file, blob: {
    content_type: [
      'application/vnd.ms-excel',
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'application/vnd.openxmlformats-officedocument.spreadsheetml.template',
      'application/vnd.ms-excel.sheet.macroEnabled.12',
      'application/vnd.ms-excel.template.macroEnabled.12',
      'application/vnd.ms-excel.addin.macroEnabled.12',
      'application/vnd.ms-excel.sheet.binary.macroEnabled.12'
    ],
    size_range: 0..700.megabytes
  }`

**Comment by aki77** [comment]
Hello.
Please follow the steps below to check the actual content_type.

1. Remove validation
2. upload the target file
3. check the content_type of the saved ActiveStorage::Blob

This validator just checks if it matches the content_type of ActiveStorage::Blob.
