### ISSUE TITLE
How to validate or limit the number of images?

### ISSUE THREAD

**Issue by fabiantorresm** [aki77/activestorage-validator#20]
Can anyone help me to limit the number of images using has_many_attached?

**Comment by aki77** [comment]
I don't think it is the role of this gem to limit the number.
It should be possible to solve this problem by defining a simple validation method.

```ruby
FILES_LIMIT = 3

has_many_attached :files
validate :validate_files_limit

def validate_files_limit
  if files.size > FILES_LIMIT
    errors.add(:files, :over_limit)
  end
end
```

**Comment by fabiantorresm** [comment]
thanks, i will try it.
