### ISSUE TITLE
Would be nice to validate if a PDF has been selected for upload.

### ISSUE THREAD

**Issue by JTensai** [aki77/activestorage-validator#21]

**Comment by aki77** [comment]
Do you mean you want to define the following?

```ruby
validates :file, presence: true, blob: { content_type: :pdf }
```

**Comment by JTensai** [comment]
Yes, that is exactly what I am looking for.

**Comment by aki77** [comment]
If you define it as follows, it should work as desired.

```ruby
validates :file, presence: true, blob: { content_type: 'application/pdf' }
```

The options that can be specified in the symbol are only the types that are defined as methods in rails.

https://github.com/rails/rails/blob/2f012f74ccdb42ea88363484770dd6cd5e82fc93/activestorage/app/models/active_storage/blob.rb#L175-L192
