### ISSUE TITLE
Feature request: validate if an uploaded file is an image without depending on a spoof'able content-type

### ISSUE THREAD

**Issue by nickjj** [aki77/activestorage-validator#26]
Hi,

The content type of a file can be spoofed which could allow someone to upload an executable file with the content type of jpg. This could allow your app to throw exceptions if it tries to perform image operations on an executable.

Usually the way to determine if something is an image is to read in the first few bytes of the file looking for a specific sequence of bytes. I haven't gotten to implementing something like this with Ruby but with Python the `imghdr` standard library module has a `imghr.what` function to call which lets you pass in a byte stream or file and it'll return back what format the file is in (jpg, png, etc.).

It's nice to be able to do this on a byte stream instead of a file because if you're uploading things as a stream you can determine if it's an image or not very quickly without uploading the entire file beforehand.

I suppose this would involve introducing a new validator that lets you whitelist a set of valid image formats and it could default to the common case of jpg, jpeg, png and webp. What do you think? Maybe this could be done using the Vips library or the `image_processing` gem since this is a requirement of Active Storage?

**Comment by aki77** [comment]
This gem validates based on the content type detected by activestorage.
If you have problems with activestorage content type detection, please send a request to the rails repository.

**Comment by nickjj** [comment]
Thanks, the content type is spoofable btw, it's just the nature of how the internet works, it's a header. That's why I suggested checking out the first couple of bytes of a file.

**Comment by aki77** [comment]
Thanks.
Activestorage uses [marcel](https://github.com/rails/marcel).

> Marcel attempts to choose the most appropriate content type for a given file by looking at the binary data, the filename, and any declared type (perhaps passed as a request header).

I believe `marcel` even checks the contents of the files.
Please let me know if I am misunderstanding something.

https://github.com/rails/rails/blob/887dc9af6cc4de9761817b8e3d2228a5a1af9802/activestorage/app/models/active_storage/blob.rb#L381-L383

**Comment by nickjj** [comment]
Oh interesting, I didn't know it looked at the binary data, although that function you linked looks like it could be related to header information only but I'll admit I didn't trace the code.
