### ISSUE TITLE
No default error messages for content_type and max_size_error

### ISSUE THREAD

**Issue by shanereddy** [aki77/activestorage-validator#3]
The current default informs the user to add a locale entry for the specific attribute errors.
I have created a fix where I have default error messages instead.
```ruby
en:
  activerecord:
    errors:
      messages:
        content_type: "is not a valid file format"
        max_size_error: "is not within valid size range"
```
I cannot push my branch up to your repo to create a PR, you need to probably allow that before anyone can contribute.

**Comment by mldoscar** [comment]
> The current default informs the user to add a locale entry for the specific attribute errors.
> I have created a fix where I have default error messages instead.
> 
> ```ruby
> en:
>   activerecord:
>     errors:
>       messages:
>         content_type: "is not a valid file format"
>         max_size_error: "is not within valid size range"
> ```
> 
> I cannot push my branch up to your repo to create a PR, you need to probably allow that before anyone can contribute.

Check this out: https://github.com/mldoscar/activestorage-validator

**Comment by aki77** [comment]
Thanks for the report.
Locale files was added in version 0.1.1.

**Comment by mldoscar** [comment]
I've just found this translation issue in japanese translation:

https://github.com/aki77/activestorage-validator/blob/6d9b480ea8286b54601bfa426b02f8778a24da7b/config/locales/ja.yml#L6

it should be like:

```
min_size_error: "を%{min_size}以上のサイズにしてください。"
```

**Comment by aki77** [comment]
@mldoscar Thanks! 👍
