### ISSUE TITLE
File Type Validation does not check if extension and MIME Type match

### ISSUE THREAD

**Issue by helphop** [aki77/activestorage-validator#8]
I have tested the validation by changing the extension of a file.  For example I took a file called 'test.pdf' and changed it to 'test.docx'.  I validate as follows:

validates :file, presence: true, blob: { content_type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'}

This passes. Shouldn't the validation fail since this is really a pdf and not a docx document?

**Comment by aki77** [comment]
This gem uses the activestorage content type guess as is.
The following may be helpful.
https://github.com/rails/rails/pull/32833
