### ISSUE TITLE
Compatibility with Rails 6

### ISSUE THREAD

**Issue by cseelus** [aki77/activestorage-validator#9]
Currently installing ActiveStorage Validator with Rails 6 (Beta 2) fails with `activestorage-validator (~> 0.1.2) was resolved to 0.1.2, which depends on rails (~> 5.2.0)`.

Is there anything blocking the use with Rails 6 or just not tested yet?

**Comment by aki77** [comment]
Sorry.
I missed it.
0.1.3 has been released!
